### ISSUE TITLE
Opening messages is slow

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#10384]
### Steps to reproduce

1. Open the app
2. Click on a message
3. Click on another message

### Expected behavior

Fast switching

### Actual behavior

Mediocre to slow switching. HTML messages are worse than plain text messages.

### Mail app version

4.0

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
Thank you for the feedback, @9-FS. Could you please open the browser developer console, switch to the network tab, reload the page and try to find the specific requests which are slow, if any? That should help narrowing it down.

**Comment by solderdev** [comment]
FYI - had the same problem both with Nextcloud Mail AND Snappymail.
The cause was a bad DNS configuration:
* Nextcloud running in Docker
* local DNS server (Technitium/Unbound/pihole) running in Docker on the same machine
* Docker internal network: 172.16.0.0
* LAN-IP: 192.168.1.10 --> the local router sets this (server IP) as DNS for all clients in LAN
* Server host-OS and therefore Docker daemon gets it's own IP assigned as DNS server (via DHCP)
* DNS lookup of mailserver-URL from Nextcloud via 192.168 IP fails (something about docker networking)

Solution:
in the docker-compose file of the DNS server, make sure port 53 is bound to the correct host-IP:
```
ports:
      - 192.168.1.10:53:53/udp
      - 192.168.1.10:53:53/tcp
```

Could you please check if you run a similar setup?
Easy test: set s/t like 1.1.1.1 as host-OS DNS and restart Docker daemon.

**Comment by 9-FS** [comment]
@ChristophWurst Unfortunately, it's incosistent. The requests that take multiple seconds all have in common that they are all JSON data from Google Mail and are not displayed in a pure text fashion. In contrast, the mails I have imported from my university server seem to be text only and load instantaneously.

@solderdev This is a pretty similar setup to mine, I just have my Technitium DNS server in its own network `br0` under `192.168.0.3` and my router advertises that IP to all devices in the network as DNS server. From the console of other containers like Nextcloud, that are in the default `bridge` network, I've tried some `nslookup` and `ping 192.168.0.3` and they were all instantaneous. I post my docker composes for Technitium and Nextcloud down here just in case it might help.

```
services:
    technitium:
        container_name: "technitium"
        image: "technitium/dns-server:13.3.0"
        environment:
            HOST_OS: "Unraid"
            TZ: "UTC"
            TCP_PORT_5380: 5380
            UDP_PORT_53: 53
        volumes:
            - "/mnt/user/appdata/technitium/:/etc/dns/:rw"
        user: "99:100"
        networks:
            br0:
                ipv4_address: "192.168.0.3"
                ipv6_address: "fd00::9e6b:ff:fe2e:d542"
        sysctls:
            net.ipv4.ip_local_port_range: "1024 65000"
        restart: "always"
        deploy:
            resources:
                limits:
                    memory: "1G"

networks:
    br0:
        external: true
```

```
services:
    mariadb:
        container_name: "nextcloud_mariadb"
        image: "mariadb:11.4.4"
        environment:
            HOST_OS: "Unraid"
            TZ: "UTC"
            # MARIADB_DATABASE: ""
            # MARIADB_PASSWORD: ""
            MARIADB_RANDOM_ROOT_PASSWORD: yes
            MARIADB_USER: "felix"
        env_file: ".env"
        volumes:
            - "/mnt/user/appdata/nextcloud/mariadb/config/:/etc/mysql/conf.d:rw"
            - "/mnt/user/appdata/nextcloud/mariadb/data/:/var/lib/mysql/:rw"
        user: "99:100"
        network_mode: "bridge"
        ports:
            - "3306:3306"
        deploy:
            resources:
                limits:
                    memory: "1G"

    redis:
        container_name: "nextcloud_redis"
        image: "redis:7.4.1"
        environment:
            HOST_OS: "Unraid"
            TZ: "UTC"
        network_mode: "bridge"
        ports:
            - "6379:6379"
        deploy:
            resources:
                limits:
                    memory: "1G"

    nextcloud:
        container_name: "nextcloud"
        image: "nextcloud:30.0.4"
        depends_on:
            - "mariadb"
            - "redis"
        environment:
            HOST_OS: "Unraid"
            TZ: "UTC"
        volumes:
            - "/mnt/user/appdata/dlh_duty_plan_converter/calendar/:/var/www/html/data/files_external/dlh_duty_plan_converter/calendar/:rw"
            - "/mnt/user/appdata/nextcloud/nextcloud/:/var/www/html:rw"
            - "/mnt/user/nextcloud/backup/:/var/www/html/data/files_external/backup/:rw"
            - "/mnt/user/nextcloud/Bauer Maria/:/var/www/html/data/Bauer Maria/:rw"
            - "/mnt/user/nextcloud/Koo Felix/:/var/www/html/data/Koo Felix/:rw"
            - "/mnt/user/nextcloud/media/:/var/www/html/data/files_external/media/:rw"
        user: "99:100"
        network_mode: "bridge"
        ports:
            - "8666:80"
        deploy:
            resources:
                limits:
                    memory: "1G"

    nextcloud_cronjob_runner:
        container_name: "nextcloud_cronjob_runner"
        image: "rcdailey/nextcloud-cronjob:latest"
        depends_on:
            - "nextcloud"
        environment:
            HOST_OS: "Unraid"
            TZ: "UTC"
            NEXTCLOUD_CONTAINER_NAME: "nextcloud"
            NEXTCLOUD_CRON_MINUTE_INTERVAL: 5
            NEXTCLOUD_EXEC_SHELL: "bash"
            NEXTCLOUD_EXEC_USER: 99
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        network_mode: "bridge"
        deploy:
            resources:
                limits:
                    memory: "1G"
```

I'm currently further looking into perhaps tweaking some Google Mail or IMAP settings...

**Comment by 9-FS** [comment]
@ChristophWurst Unfortunately, it's incosistent. The requests that take multiple seconds all have in common that they are all JSON data from Google Mail and are not displayed in a pure text fashion. In contrast, the mails I have imported from my university server seem to be text only and load instantaneously.

@solderdev This is a pretty similar setup to mine, I just have my Technitium DNS server in its own network `br0` under `192.168.0.3` and my router advertises that IP to all devices in the network as DNS server. From the console of other containers like Nextcloud, that are in the default `bridge` network, I've tried some `nslookup` and `ping 192.168.0.3` and they were all instantaneous. I post my docker composes for Technitium and Nextcloud down here just in case it might help.

```
services:
    technitium:
        container_name: "technitium"
        image: "technitium/dns-server:13.3.0"
        environment:
            HOST_OS: "Unraid"
            TZ: "UTC"
            TCP_PORT_5380: 5380
            UDP_PORT_53: 53
        volumes:
            - "/mnt/user/appdata/technitium/:/etc/dns/:rw"
        user: "99:100"
        networks:
            br0:
                ipv4_address: "192.168.0.3"
                ipv6_address: "fd00::9e6b:ff:fe2e:d542"
        sysctls:
            net.ipv4.ip_local_port_range: "1024 65000"
        restart: "always"
        deploy:
            resources:
                limits:
                    memory: "1G"

networks:
    br0:
        external: true
```

```
services:
    mariadb:
        container_name: "nextcloud_mariadb"
        image: "mariadb:11.4.4"
        environment:
            HOST_OS: "Unraid"
            TZ: "UTC"
            # MARIADB_DATABASE: ""
            # MARIADB_PASSWORD: ""
            MARIADB_RANDOM_ROOT_PASSWORD: yes
            MARIADB_USER: "felix"
        env_file: ".env"
        volumes:
            - "/mnt/user/appdata/nextcloud/mariadb/config/:/etc/mysql/conf.d:rw"
            - "/mnt/user/appdata/nextcloud/mariadb/data/:/var/lib/mysql/:rw"
        user: "99:100"
        network_mode: "bridge"
        ports:
            - "3306:3306"
        deploy:
            resources:
                limits:
                    memory: "1G"

    redis:
        container_name: "nextcloud_redis"
        image: "redis:7.4.1"
        environment:
            HOST_OS: "Unraid"
            TZ: "UTC"
        network_mode: "bridge"
        ports:
            - "6379:6379"
        deploy:
            resources:
                limits:
                    memory: "1G"

    nextcloud:
        container_name: "nextcloud"
        image: "nextcloud:30.0.4"
        depends_on:
            - "mariadb"
            - "redis"
        environment:
            HOST_OS: "Unraid"
            TZ: "UTC"
        volumes:
            - "/mnt/user/appdata/dlh_duty_plan_converter/calendar/:/var/www/html/data/files_external/dlh_duty_plan_converter/calendar/:rw"
            - "/mnt/user/appdata/nextcloud/nextcloud/:/var/www/html:rw"
            - "/mnt/user/nextcloud/backup/:/var/www/html/data/files_external/backup/:rw"
            - "/mnt/user/nextcloud/Felix/:/var/www/html/data/Felix/:rw"
            - "/mnt/user/nextcloud/media/:/var/www/html/data/files_external/media/:rw"
        user: "99:100"
        network_mode: "bridge"
        ports:
            - "8666:80"
        deploy:
            resources:
                limits:
                    memory: "1G"

    nextcloud_cronjob_runner:
        container_name: "nextcloud_cronjob_runner"
        image: "rcdailey/nextcloud-cronjob:latest"
        depends_on:
            - "nextcloud"
        environment:
            HOST_OS: "Unraid"
            TZ: "UTC"
            NEXTCLOUD_CONTAINER_NAME: "nextcloud"
            NEXTCLOUD_CRON_MINUTE_INTERVAL: 5
            NEXTCLOUD_EXEC_SHELL: "bash"
            NEXTCLOUD_EXEC_USER: 99
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        network_mode: "bridge"
        deploy:
            resources:
                limits:
                    memory: "1G"
```

I'm currently further looking into perhaps tweaking some Google Mail or IMAP settings...
