### ISSUE TITLE
Date and time issue with our mails

### ISSUE THREAD

**Issue by CamZie** [nextcloud/mail#3386]
Hello,

I would like to report our issue with the date and time of our mails when using the Mail app on our Nextcloud 18 installations.

**Actual behaviour**
The dates are showing wrong like either very very old like from the 19's or from the future like .e.g 2036 etc. On our webmail the dates are showing correctly.

**Nextcloud versions currently tested:** 18.0.6 and 18.0.7
**Mail app version** 1.4.1

**Comment by GretaD** [comment]
Hello @CamZie,  can you please send us any error shown on your web console when you open Nextcloud mail app, and the log from nextcloud.log. 
I tried to reproduce it on my 18.6 and everything looks fine there.

**Comment by CamZie** [comment]
@GretaD Please find below the web console logs when the app has been accessed:
```
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).                      global.js:10
```
There seems to be no logs on Nextcloud regarding this.

**Comment by ChristophWurst** [comment]
Could you inspect the table `oc_mail_messages`, try to find the message by subject and see what `sent_at` is set to?

**Comment by CamZie** [comment]
@ChristophWurst as requested you can find below some examples of the emails showing the wrong date:

The first one is 14 years old and the second example is 8 years in the future

<details>
<Summary> oc_mail_messages examples </Summary>

```
*************************** 2. row ***************************
                id: 83867
               uid: 375
        message_id: **REMOVED***
        mailbox_id: 740
           subject: **REMOVED***
           sent_at: 1163581991
     flag_answered: 0
      flag_deleted: 0
        flag_draft: 0
      flag_flagged: 0
         flag_seen: 1
    flag_forwarded: 0
         flag_junk: 0
      flag_notjunk: 0
  flag_attachments: 0
    flag_important: 0
structure_analyzed: 1
      preview_text: 
        updated_at: 1597646973
*************************** 407. row ***************************
                id: 96273
               uid: 411
        message_id: ***REMOVED***
        mailbox_id: 740
           subject: **REMOVED***
           sent_at: 1846463571
     flag_answered: 0
      flag_deleted: 0
        flag_draft: 0
      flag_flagged: 0
         flag_seen: 1
    flag_forwarded: 0
         flag_junk: 0
      flag_notjunk: 0
  flag_attachments: 0
    flag_important: 1
structure_analyzed: 1
      preview_text: 
        updated_at: 1597646811
```
</details>
