### ISSUE TITLE
"Add mail account" button looks wonky

### ISSUE THREAD

**Issue by auroraanna** [nextcloud/mail#8714]
### Steps to reproduce

1. Open the app
2. Setup and account
3. Open the navigation on the left
4. Click "Mail settings"

### Expected behavior

- The "Add mail account" should the the full width that is available inside it's container like the other buttons in navigation.
- The "Add mail account" button icon and text should be aligned left or center like the other buttons.

### Actual behavior

The "Add mail account" button is not full width and it's icon and text and not aligned left or center. The button's icon and text look like they're aligned right but actually there is extra padding on the left:
```css
.app-settings-button.button.primary.new-button[data-v-16724163] {
    color: var(--color-primary-element-text);
    padding-left: 34px;
    gap: 4px;
    width: fit-content;
}
```
![image](https://github.com/nextcloud/mail/assets/81317317/ca918f89-4cc8-41d7-b704-ac5bc7f1436c)

### Mail app version

3.4.0-beta.1

### Mailserver or service

Mailcow (mail server)

### Operating system

NixOS 23.11.2023080 (Linux)

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

MariaDB
